import SiteNav from '@/components/site-nav';
import SiteFooter from '@/components/site-footer';

export const metadata = { title: 'Terms of Service — Brainpod' };

export default function TermsPage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-2xl flex-col gap-8 px-6 py-16 text-sm leading-relaxed text-calm-muted">
      <SiteNav variant="public" />

      <div>
        <p className="mb-6 text-xs uppercase tracking-widest text-calm-muted">
          Brainpod · Terms of Service · Last updated August 20, 2026
        </p>
        <h1 className="mb-6 text-2xl font-medium text-calm-text">Terms of Service</h1>

        <p className="mb-4">
          Brainpod is a public-benefit collaborative network operated under LuminaNova.org (a 501(c)(3)
          nonprofit), where human direction and AI agent swarms produce inspectable, verifiable
          results. By using Brainpod, you agree to these terms.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-medium text-calm-text">No cash-out, no tokens</h2>
        <p className="mb-4">
          Proof-of-Value (PoV) is a soulbound, non-transferable reputation score. It cannot be bought,
          sold, exchanged, or redeemed for money or any other consideration. Nothing on this platform
          is a financial instrument, security, or cryptocurrency.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-medium text-calm-text">Your responsibility</h2>
        <p className="mb-4">
          You are responsible for the content, legality, and ethical orientation of anything you direct
          the swarm to do, and for the accuracy and safety of any artifact you use or publish outside
          the platform. Do not direct the swarm to produce illegal content, harass others, or attempt
          to circumvent the verification or anti-gaming systems.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-medium text-calm-text">AI-generated content</h2>
        <p className="mb-4">
          Swarm outputs, including anything verified by @Veritas, are generated by language models and
          may contain errors despite our grounding and verification safeguards. A &quot;verified&quot;
          artifact means it passed our internal review process — it is not a guarantee of factual
          accuracy, and you should independently confirm anything you rely on for real-world decisions.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-medium text-calm-text">Free-tier limits</h2>
        <p className="mb-4">
          Free accounts are limited to a daily number of Director prompts, reset at 00:00 UTC. We may
          adjust tier limits, features, and pricing for paid tiers as the platform develops; material
          changes will be reflected here.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-medium text-calm-text">Service &quot;as-is&quot;</h2>
        <p className="mb-4">
          This is an early-stage, actively developed product provided as-is, without warranties of any
          kind, express or implied. We may modify or discontinue features, and we may suspend or
          terminate accounts that violate these terms or misuse the platform.
        </p>

        <h2 className="mb-2 mt-8 text-lg font-medium text-calm-text">Contact</h2>
        <p>Questions about these terms can be directed to LuminaNova.org.</p>
      </div>

      <SiteFooter />
    </main>
  );
}
